config/routes.rb
# -*- encoding : utf-8 -*-

Rails.application.routes.draw do
  # /login, /logout
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { sessions: 'sessions' }
  # /login, /logout

  # api/v1
  get 'api/v1/auth' => 'api/v1/auth#index'
  get 'api/v1/sections' => 'api/v1/sections#index'
  get 'api/v1/section_file/:id/translations' => 'api/v1/section_file#translations'
  get 'api/v1/section/:id/files' => 'api/v1/section#files'
  post 'api/v1/translations/:id/toggle_approved' => 'api/v1/translations#toggle_approved'
  # api/v1

  scope :section do
    get ':id/translations' => 'section#translations', as: :section_translations
    get ':id/drop_non_actual' => 'section#drop_non_actual', as: :section_drop_non_actual
  end

  scope :section_file do
    get ':id/translations' => 'section_file#translations', as: :section_file_translations
    get ':id/drop_non_actual' => 'section_file#drop_non_actual', as: :section_file_drop_non_actual
  end

  scope :translation do
    get ':id/approve' => 'translation#approve', as: :translation_approve
  end

  root :to => 'root#index'
end

app/views/layouts/_footer.html.erb
<div class="text-center">
  <p>
    <small class="text-muted">gorko.plusmedia.ru &copy; 2017</small>
  </p>
</div>

app/views/layouts/_header.html.erb
<!-- header -->
<header id="header" class="app-header navbar" role="menu">
  <!-- navbar header -->
  <div class="navbar-header bg-primary">
    <button class="pull-right visible-xs dk" ui-toggle-class="show" target=".navbar-collapse">
      <i class="glyphicon glyphicon-cog"></i>
    </button>
    <button class="pull-right visible-xs" ui-toggle-class="off-screen" target=".app-aside" ui-scroll="app">
      <i class="glyphicon glyphicon-align-justify"></i>
    </button>
    <!-- brand -->
    <a href="#/" class="navbar-brand text-lt">
      <span class="hidden-folded m-l-xs"><%= Rails.configuration.site_name %></span>
    </a>
    <!-- / brand -->
  </div>
  <!-- / navbar header -->

  <!-- navbar collapse -->
  <div class="collapse pos-rlt navbar-collapse box-shadow bg-white-only">

    <!-- nabar right -->
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <%= link_to raw('<span>Logout</span>'), destroy_user_session_path, method: :delete %>
      </li>
    </ul>
    <!-- / navbar right -->
  </div>
  <!-- / navbar collapse -->
</header>
<!-- / header -->

app/views/layouts/_navbar.html.erb
<%= render partial: 'layouts/header' %>

<!-- aside -->
<aside id="aside" class="app-aside hidden-xs bg-dark">
  <div class="aside-wrap">
    <div class="navi-wrap">

      <!-- nav -->
      <nav ui-nav class="navi clearfix">
        <ul class="nav">
			<li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
				<span>Разделы</span>
			</li>

			<% @sections.each do |section| %>
				<li class="<%= section.li_class(@section) %>">
					<a href="<%= section_translations_path(section) %>" class="auto">
						<span class="pull-right text-muted">
							<i class="fa fa-fw fa-angle-right text"></i>
							<i class="fa fa-fw fa-angle-down text-active"></i>
						</span>
						<b class="label bg-primary pull-right"><%= section.files.count %></b>

						<span><%= section.name %></span>
					</a>

					<ul class="nav nav-sub dk" style="">
						<li class="nav-sub-header">
							<a href="<%= section_translations_path(section) %>"><span><%= section.name %></span></a>
						</li>
						<% section.files.each do |file| %>
							<li>
								<a href="<%= section_file_translations_path(file) %>">
									<b class="label bg-success pull-right"><%= file.translations.count %></b>
									<span><%= file.name %></span>
								</a>
							</li>
						<% end %>
					</ul>
				</li>
			<% end %>
        </ul>
      </nav>
      <!-- nav -->

    </div>
  </div>
</aside>
<!-- / aside -->

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/i/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= Rails.configuration.site_name %></title>
  <meta name="description" content="">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="/css/animate.css" type="text/css"/>
  <link rel="stylesheet" href="/css/font-awesome.min.css" type="text/css"/>
  <link rel="stylesheet" href="/css/bootstrap/bootstrap.css" type="text/css"/>
  <link rel="stylesheet" href="/css/font.css" type="text/css"/>
  <link rel="stylesheet" href="/css/app.css" type="text/css"/>

  <script src="/js/jquery/jquery.js"></script>
  <script src="/js/jquery/throttle.js"></script>


  <%= javascript_include_tag 'application' %>
  <script src="/js/bootstrap/bootstrap.min.js"></script>

  <link rel="stylesheet" href="/css/simple-line-icons.css" type="text/css"/>
</head>
<body>
<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6.
     chromium.org/developers/how-tos/chrome-frame-getting-started -->
<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a
    different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a>
    to experience this site.</p><![endif]-->

<div class="app app-header-fixed">
  <% if root_page? %>
      <link rel="stylesheet" href="/css/root.css" type="text/css"/>
      <%= yield %>
  <% else %>
      <% if current_user %>

          <!-- content -->
          <%= render partial: 'layouts/navbar' %>

          <div id="content" class="app-content" role="main">
            <div class="app-content-body ">

              <%= yield %>

            </div>
          </div>

      <% else %>
          <%= yield %>
      <% end %>
  <% end %>
</div>

<script src="/js/ui-load.js"></script>
<script src="/js/ui-jp.config.js"></script>
<script src="/js/ui-jp.js"></script>
<script src="/js/ui-toggle.js"></script>
<script src="/js/ui-client.js"></script>
<script src="/js/ui-actual.js"></script>

</body>
</html>